import "server-only";
import { prisma, withPrismaRetry } from "@/lib/prisma";
import type { TeamPredictPayload } from "@/lib/predictFixtureCompute";
import { buildPredictionFromStoredData } from "@/lib/server/cachedPrediction";

/** デフォルト 24 時間。無料枠の日次上限を考慮し長めに。環境変数で上書き可。 */
const TTL_MS =
  Math.max(1, Number(process.env.PREDICT_CACHE_TTL_HOURS ?? 24)) * 3600 * 1000;

function cacheId(teamId: string) {
  return `team:${teamId}`;
}

async function persistOk(
  teamId: string,
  payload: TeamPredictPayload,
  fetchedAt: Date,
  expiresAt: Date
) {
  const id = cacheId(teamId);
  const matchId =
    typeof payload.fixture?.id === "number" ? payload.fixture.id : null;
  await withPrismaRetry("PredictionCache.upsert OK", () =>
    prisma.predictionCache.upsert({
      where: { id },
      create: {
        id,
        teamId: Number(teamId),
        matchId,
        homeTeamId: null,
        awayTeamId: null,
        payload: payload as object,
        fetchedAt,
        expiresAt,
        status: "OK",
        errorNote: null,
      },
      update: {
        teamId: Number(teamId),
        matchId,
        payload: payload as object,
        fetchedAt,
        expiresAt,
        status: "OK",
        errorNote: null,
      },
    })
  );
}

export type PredictJsonResponse = Record<string, unknown>;

function isUpcomingPrediction(payload: TeamPredictPayload): boolean {
  if (payload.fixture?.status === "FINISHED") return false;
  const utcDate = payload.fixture?.utcDate;
  if (!utcDate) return true;
  const kickoff = new Date(utcDate).getTime();
  return Number.isFinite(kickoff) && kickoff > Date.now();
}

/**
 * キャッシュ優先で予想 JSON を組み立てる（ルート・SSR・cron から利用）。
 */
export async function getPredictJsonForTeam(
  teamId: string
): Promise<{ json: PredictJsonResponse; status: number }> {
  const id = cacheId(teamId);
  const now = new Date();

  let row: Awaited<ReturnType<typeof prisma.predictionCache.findUnique>> = null;
  try {
    row = await withPrismaRetry("PredictionCache.findUnique", () =>
      prisma.predictionCache.findUnique({ where: { id } })
    );
  } catch (e) {
    console.warn("[predictCache] DB read failed", e);
  }

  const freshEnough = row && row.expiresAt > now;
  const cachedOk =
    row?.status === "OK" && row.payload != null
      ? (row.payload as unknown as TeamPredictPayload)
      : null;

  // Keep a still-upcoming prediction exactly as generated by the original
  // model. Reading it never starts an upstream refresh.
  if (freshEnough && cachedOk && isUpcomingPrediction(cachedOk)) {
    return {
      json: {
        ...cachedOk,
        meta: {
          source: "cache",
          fetchedAt: row!.fetchedAt.toISOString(),
          expiresAt: row!.expiresAt.toISOString(),
        },
      },
      status: 200,
    };
  }

  if (!freshEnough && cachedOk && isUpcomingPrediction(cachedOk)) {
    return {
      json: {
        ...cachedOk,
        meta: {
          source: "stale",
          fetchedAt: row!.fetchedAt.toISOString(),
          expiresAt: row!.expiresAt.toISOString(),
        },
      },
      status: 200,
    };
  }

  // EMPTY and expired/past predictions are superseded by the durable league
  // snapshots. This calculation is local and performs zero football-data.org
  // requests.
  const stored = await buildPredictionFromStoredData(Number(teamId));
  if (stored) {
    const payload = stored;
    const expiresAt = new Date(now.getTime() + TTL_MS);
    await persistOk(teamId, payload, now, expiresAt).catch((error) =>
      console.warn("[predictCache] stored prediction persist failed", error)
    );
    return {
      json: {
        ...payload,
        meta: {
          source: "stored_league_cache",
          fetchedAt: now.toISOString(),
          expiresAt: expiresAt.toISOString(),
        },
      },
      status: 200,
    };
  }

  // Keep the last successful prediction when no newer stored fixture is available.
  if (cachedOk) {
    return {
      json: {
        ...cachedOk,
        meta: {
          source: "stale",
          fetchedAt: row!.fetchedAt.toISOString(),
          expiresAt: row!.expiresAt.toISOString(),
        },
      },
      status: 200,
    };
  }

  if (row?.status === "EMPTY" && row.payload != null) {
    const empty = row.payload as Record<string, unknown>;
    return {
      json: {
        ...empty,
        meta: {
          source: freshEnough ? "cache" : "stale",
          fetchedAt: row.fetchedAt.toISOString(),
          expiresAt: row.expiresAt.toISOString(),
        },
      },
      status: 200,
    };
  }

  return {
    json: {
      message: "データ更新待ちです。キャッシュ更新後に表示されます。",
      meta: { source: "preparing", reason: "cache_miss" },
    },
    status: 200,
  };
}
